# Generated by Django 4.2.5 on 2023-09-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_photo_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
