# Generated by Django 4.1 on 2024-01-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0006_photo_user_alter_photo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='publicada',
            field=models.BooleanField(default=True),
        ),
    ]
