# Generated by Django 4.2.5 on 2023-09-24 01:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_photo_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='data',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
